type Icon =
  | 'add-outline'
  | 'bookmark'
  | 'bookmark-outline'
  | 'chatbubble-outline'
  | 'checkmark-circle'
  | 'compass'
  | 'compass-outline'
  | 'heart-outline'
  | 'home'
  | 'home-outline'
  | 'logo-twitter'
  | 'mail'
  | 'mail-outline'
  | 'notifications'
  | 'notifications-outline'
  | 'person'
  | 'person-outline'
  | 'reader'
  | 'reader-outline'
  | 'repeat-outline'
  | 'search-outline'
  | 'share-outline';

export default Icon;
